/*
 * Smobilpay S3P API
 * Smobilpay Third Party API FOR PAYMENT COLLECTIONS
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.maviance.s3pjavaclient.api.functional;

import org.maviance.s3pjavaclient.api.AccountApi;

import org.junit.Assert;
import org.junit.Before;
import org.maviance.s3pjavaclient.ApiClient;
import org.maviance.s3pjavaclient.ApiException;
import org.maviance.s3pjavaclient.model.Account;
import org.junit.Test;

/**
 * API tests for AccountApi against test environment
 */

public class AccountApiTest {

    private AccountApi api;

    @Before
    public void setup() {
        // staging credentials
        ApiClient apiClient = new ApiClient(
            "https://s3p.smobilpay.staging.maviance.info/v2",
            "10AD3F95-9156-A86C-A1F0-733231FF5993",
            "3AF50207-CCEC-8959-6934-A29D1DD78298"
        );
        api = new AccountApi(apiClient);
    }

    /**
     * Retrieve account information and remaining account balance
     *
     * This endpoint returns the user’s account information – most notably the current balance of the user.
     * Calling this service before and after **each** collection in order to retrieve the current limits and/or balance is **highly discouraged**.
     * The recommended approach is as follows:
     * 1. Only a successful payment collection transaction will affect the account balance.
     * The corresponding endpoint will also return the current account balance after the collection in its result payload.
     * 2. For unsuccessful payment transactions, the account balance will not be affected.
     * The error message returns a verbose message as to why the transaction failed.
     * There is no need to recheck the account after each error.
     *
     * @throws ApiException if the Api call fails
     */

    @Test(expected = ApiException.class)
    public void accountGetTest() throws ApiException {
        String xApiVersion = "1.0.0";
        Account response = api.accountGet(xApiVersion);
        Assert.assertNotNull("Account response null", response);
    }
}
