/*
 * Smobilpay S3P API STANDARD
 * Smobilpay Third Party STANDARD API FOR PAYMENT COLLECTIONS
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.maviance.s3pjavaclient.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * I18nText
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-20T16:37:47.602Z")
public class I18nText {
  @SerializedName("language")
  private String language = null;

  @SerializedName("localText")
  private String localText = null;

  public I18nText language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Target language to retrieve the translations for (e.g. &#39;en&#39;, &#39;fr&#39;, etc.)
   * @return language
  **/
  @ApiModelProperty(required = true, value = "Target language to retrieve the translations for (e.g. 'en', 'fr', etc.)")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public I18nText localText(String localText) {
    this.localText = localText;
    return this;
  }

   /**
   * localized text
   * @return localText
  **/
  @ApiModelProperty(required = true, value = "localized text")
  public String getLocalText() {
    return localText;
  }

  public void setLocalText(String localText) {
    this.localText = localText;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    I18nText i18nText = (I18nText) o;
    return Objects.equals(this.language, i18nText.language) &&
        Objects.equals(this.localText, i18nText.localText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, localText);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class I18nText {\n");
    
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    localText: ").append(toIndentedString(localText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

