/*
 * Smobilpay S3P API STANDARD
 * Smobilpay Third Party STANDARD API FOR PAYMENT COLLECTIONS
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.maviance.s3pjavaclient.api;

import org.junit.Ignore;
import org.junit.Test;
import org.maviance.s3pjavaclient.ApiException;
import org.maviance.s3pjavaclient.model.Ping;

/**
 * API tests for ChecksApi
 */
@Ignore
public class ChecksApiTest {

	private final ChecksApi api = new ChecksApi();

	/**
	 * Run a ping to check on the availability of the api
	 *
	 * This endpoint simply checks the existence and validity of the request on the
	 * server by returning a valid response object or an error message. Its primary
	 * purpose is to provide a feedback on whether or not the API is available. It
	 * also provides the current server time and timezone
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void pingGetTest() throws ApiException {
		Ping response = api.pingGet();

		// TODO: test validations
	}

}
