/*
 * Smobilpay S3P API
 * Smobilpay Third Party API FOR PAYMENT COLLECTIONS
 *
 * OpenAPI spec version: 3.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.maviance.s3pjavaclient.api.unit;

import org.maviance.s3pjavaclient.ApiException;
import org.maviance.s3pjavaclient.api.AccountValidationApi;
import org.maviance.s3pjavaclient.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountValidationApi
 */
@Ignore
public class AccountValidationApiTest {

    private final AccountValidationApi api = new AccountValidationApi();

    
    /**
     * Verify service number
     *
     * For services that support verification (indicated by the \&quot;isVerifiable\&quot; flag) the service number can be provided to this endpoint. The system will verify wether or not the service number is valid with the selected service. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verifyGetTest() throws ApiException {
        String xApiVersion = null;
        String merchant = null;
        Integer serviceid = null;
        String serviceNumber = null;
        Boolean response = api.verifyGet(xApiVersion, merchant, serviceid, serviceNumber);

        // TODO: test validations
    }
    
}
